package model

// These Go structs were generated by pasting the response into:
// https://mholt.github.io/json-to-go/

// StationResponse contains Data which contains Stations.
// This is the base struct we use to unmarshal the JSON.
type StationResponse struct {
	LastUpdated int  `json:"last_updated"`
	TTL         int  `json:"ttl"`
	Data        Data `json:"data"`
}

type Stations struct {
	StationID string  `json:"station_id"`
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	Lat       float64 `json:"lat"`
	Lon       float64 `json:"lon"`
	Capacity  int     `json:"capacity"`
}

type Data struct {
	Stations []Stations `json:"stations"`
}